customhost = "database-2.clocsq6mubfx.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Aacs3253"
customdb = "employee"
custombucket = "yapliying-employee"
customregion = "us-east-1"
